[project]
name = "template"
version = "0.1.0"
description = ""
authors = [{ name = "Hannah Herbig", email = "nothannahherbig@gmail.com" }]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff==0.0.348",
    "pre-commit==4.6.0",
    "pyupgrade==3.21.2",
]

[tool.ruff]
line-length = 88
target-version = ["py312"]
extend-select = ["I"]
extend-ignore = ["E203", "W503"]

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
